### ISSUE TITLE
Crash while reading node

### ISSUE THREAD

**Issue by laacz** [Bouni/node-red-contrib-luxtronik2-ws#5]
Seems like there has beena nother update...

```
2 Dec 15:29:33 - TypeError: Cannot read property '0' of undefined
    at /home/pi/.node-red/node_modules/node-red-contrib-luxtronik2-ws/luxtronik2-ws.js:76:49
    at Parser.<anonymous> (/home/pi/.node-red/node_modules/xml2js/lib/parser.js:306:18)
    at Parser.emit (events.js:198:13)
    at SAXParser.onclosetag (/home/pi/.node-red/node_modules/xml2js/lib/parser.js:264:26)
    at emit (/home/pi/.node-red/node_modules/sax/lib/sax.js:624:35)
    at emitNode (/home/pi/.node-red/node_modules/sax/lib/sax.js:629:5)
    at closeTag (/home/pi/.node-red/node_modules/sax/lib/sax.js:889:7)
    at SAXParser.write (/home/pi/.node-red/node_modules/sax/lib/sax.js:1436:13)
    at Parser.exports.Parser.Parser.parseString (/home/pi/.node-red/node_modules/xml2js/lib/parser.js:325:31)
    at Parser.parseString (/home/pi/.node-red/node_modules/xml2js/lib/parser.js:5:59)
nodered.service: Main process exited, code=exited, status=1/FAILURE
```

**Comment by Bouni** [comment]
Hi, this repo is no longer maintained. 

Thankfully I don't have to use nodejs anymore and moved on to [Home-Assistant](https://www.home-assistant.io/) which is written in python. If you are not forced to use nodejs I recommend to move on as well!

**Comment by laacz** [comment]
I'd be happy to, however HA is not yet on roadmap. But thanks anyway. I'll mock something up myself.
